name: "test custom action"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'action.yaml'
      - '.github/workflows/test-custom-action.yaml'

jobs:
  run-integrations:
    runs-on: ubuntu-latest
    steps:
      - name: "ブランチの切り替え"
        uses: actions/checkout@v4
      - name: "カスタムアクションの実行"
        uses: kei-s16/hitoku@feature/provide-actions
      - name: "パスの確認"
        run: which hitoku
      - run: env
        env:
          DB_ENDPOINT: "TEST_VAR_A"
          DB_USER: "TEST_VAR_B"
          DB_PASSWORD: "TEST_VAR_C"
          DB_NAME: "TEST_VAR_D"
      - name: "テスト実行(preview)"
        run: hitoku preview ./example.toml.tmpl
        working-directory: ./tests
        env:
          DB_ENDPOINT: "TEST_VAR_A"
          DB_USER: "TEST_VAR_B"
          DB_PASSWORD: "TEST_VAR_C"
          DB_NAME: "TEST_VAR_D"
      - name: "テスト実行(generate)"
        run: hitoku generate ./example.toml.tmpl example.toml
        working-directory: ./tests
        env:
          DB_ENDPOINT: "TEST_VAR_A"
          DB_USER: "TEST_VAR_B"
          DB_PASSWORD: "TEST_VAR_C"
          DB_NAME: "TEST_VAR_D"
      - name: "出力確認(ls)"
        run: ls ./tests
      - name: "出力確認(cat)"
        run: cat ./tests/example.toml

